---
- hosts: servers
  gather_facts: no
  tasks:
    - name: installing httpd
      yum: pkg=httpd state=installed
      become: true

    - name: start httpd service
      service: name=httpd state=started
      become: true
      register: httpd_output

    - name: printing httpd_output
      debug: var=httpd_output

    - name: printing status
      debug: msg="My automation is succesful."
      when: httpd_output is success
